config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "users#index"

  resources :users, only: %i[index]
  resources :foods, only: %i[index create destroy new]
  resources :recipies, only: %i[index create destroy new show] do
      resources :recipies_foods, only: %i[create destroy new]
  end
  resources :public_recipies, only: %i[index]
  resources :generate_shopping_list, only: %i[index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, Food, user_id: user.id
    can :manage, Recipe, user_id: user.id
    can :read, :all
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'food_id', dependent: :destroy
  has_many :recipes, through: :recipe_foods
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :name, presence: true
  validates :measurement_unit, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, class_name: 'RecipeFood', foreign_key: 'recipe_id', dependent: :destroy
  has_many :foods, through: :recipe_foods
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :name, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, class_name: 'Food', foreign_key: 'user_id', dependent: :destroy
  has_many :recipes, class_name: 'Recipe', foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @food = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    food = current_user.foods.new(post_params)
    respond_to do |format|
      format.html do
        if food.save
          flash[:success] = 'Created New Food Succesfully!'
          redirect_to foods_path
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to foods_path
    flash[:success] = 'Food Deleted!'
  end

  private

  def post_params
    params.require(:data).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/generate_shopping_list_controller.rb
class GenerateShoppingListController < ApplicationController
  def index
    @recipes = current_user.recipes.includes(:recipe_foods).includes(:foods)
    @sum = 0
  end
end

app/controllers/public_recipies_controller.rb
class PublicRecipiesController < ApplicationController
  def index
    @public_recipes = Recipe.where('public= true')
      .order(id: :desc).includes(:user)
      .includes(:recipe_foods).includes(:foods)
  end
end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def create
    new_recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      format.html do
        if new_recipe.save
          flash[:success] = 'New Recipe Added Succesfully!'
          redirect_to recipies_path
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipies_path
    flash[:success] = 'Recipe Deleted!'
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods
    @foods = Food.all
  end

  def new
    @recipe = Recipe.new
  end

  private

  def recipe_params
    params.require(:data).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/recipies_foods_controller.rb
class RecipiesFoodsController < ApplicationController
  def create
    recipe = Recipe.find(params[:recipy_id])
    new_recipe = recipe.recipe_foods.new(recipe_food_params)
    respond_to do |format|
      format.html do
        if new_recipe.save
          flash[:success] = 'New Ingrediet Added Succesfully!'
          redirect_to recipy_path(recipe.id)
        else
          render :new, alert: 'Error occured!'
        end
      end
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    recipe = recipe_food.recipe
    recipe_food.destroy
    redirect_to recipy_path(recipe.id)
    flash[:success] = 'Ingredient Deleted'
  end

  def new
    @foods = current_user.foods
  end

  def recipe_food_params
    params.require(:data).permit(:food_id, :quantity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/general_shopping_list_helper.rb
module GeneralShoppingListHelper
end

app/helpers/generate_shopping_list_helper.rb
module GenerateShoppingListHelper
end

app/helpers/public_recipies_helper.rb
module PublicRecipiesHelper
end

app/helpers/recipies_foods_helper.rb
module RecipiesFoodsHelper
end

app/helpers/recipies_helper.rb
module RecipiesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foods/index.html.erb
<div class="button d-flex">
	<button class="butt">
    <%= link_to "Add Food", new_food_path %>
  </button>
</div>
<div class="food-container d-flex j-center">
<table>
<tr class="head">
 <th><h3>Food</h3></th>
 <th><h3>Measurement unit</h3></th>
 <th><h3>Unit price</h3></th>
 <th><h3>Actions</h3></th>
</tr>
<% @food.each do |food|%>
<tr> 
	<td><h3><%= food.name%></h3></td>
	<td><h3><%= food.measurement_unit%></h3></td>
	<td><h3><%= food.price%></h3></td>
	<td><% if can? :distroy, food %>
     <%= button_to "Delete", food_path(food.id), method: :delete, class: "submit" %>
  <% else %>
    cannot delete
 <% end %></td>
	</tr>
	<%end%>
	</table>
</div>

app/views/foods/new.html.erb
<h1 class='d-flex a-center j-center'>Add Food</h1>

<%=form_with url: foods_path, scope: :data do |f| %>
    <div class="form-group">
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :measurement_unit, "measurement_unit:" %>
        <%= f.text_field :measurement_unit, required: true, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :price, "price:" %>
        <%= f.text_field :price, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
        <%=f.submit "Submit", class: "submit-button" %>
    </div>

<% end %>

app/views/generate_shopping_list/index.html.erb
<%if @recipes.empty?%>
  <div class='g-shop-list'>
    <h1 class='d-flex a-center j-center'>No Shopping List. Please Add Ingredients to Recipe</h1>
  </div>
<%else%>
  <div class='g-shop-list-cont d-flex f-col a-center j-center'>
      <%@recipes.each do |recipe|%>
        <% recipe.recipe_foods.each { |recipe_food| @sum += recipe_food.quantity.to_i * recipe_food.food.price.to_i  }%>
      <%end%>
     <div class='g-shop-header d-flex f-col a-center j-center'>
        <h1 class='d-flex a-center j-center'>Shopping List</h1>
        <span class='span a-center d-flex'>
        <%shopping_length = 0%>
         <%@recipes.each { |recipe| shopping_length += recipe.recipe_foods.length}%>
         <h2><%= "Amount of food items to buy: #{shopping_length}"%></h2>
         <h2><%= "Total Value of food needed: $#{@sum}"%></h2>
        </span>
    </div>
     <div class='recipe-show-table'>
        <table>
          <tr>
            <th> Food </th>
            <th> Quantity </th>
            <th> Price </th>
            
          </tr>
          <% @recipes.each do |recipe| %>
             <% recipe.recipe_foods.each do |r_food| %>
                <tr>
                   <td><%=r_food.food.name%></td>
                   <td><%="#{r_food.quantity}#{r_food.food.measurement_unit}"%></td>
                   <td><%="$#{r_food.food.price.to_i * r_food.quantity.to_i}"%></td>
               </tr>
             <%end%>
          <%end%>
        </table>
      </div>

  </div>
<%end%>

app/views/public_recipies/index.html.erb
<%if @public_recipes.empty? %>
  <div class='recipe-index-page public-recipe-page d-flex a-center j-center'>
    <h1>No Public recipes available<h1>
  </div>
<%else%>
    <div  class='recipe-cont public-recipe d-flex f-col j-center a-center'>
        <%@public_recipes.each do |public_recipe|%>
       <% sum = 0%>
       <%= link_to recipy_path(public_recipe.id) do %>
         <div class='p-c d-flex a-center j-center'>
            <div class ='recipe-name-delete public-recipe-name-delete d-flex j-center f-col' >
              <h1><%= public_recipe.name %></h1>
              <h2><%= "By #{public_recipe.user.name}"%></h2>
            </div>
            <div class='description public-recipe-food-desc d-flex f-col a-center j-center'>
                <p><%="Total food items: #{public_recipe.recipe_foods.length}"%></p>
                <%public_recipe.recipe_foods.each {|r_food| sum += r_food.quantity.to_i * r_food.food.price.to_i}%>
                <p><%="Total Price $#{sum}"%></p>
            </div>
         </div>
       <%end%>
    <%end%>
    </div>
<%end%>

app/views/recipies/index.html.erb
<h1>Place to view my recipe</h1>

<%if @recipes.empty?%>
  <div class='recipe-index-page d-flex a-center j-center'>
    <h1>You have no recipies. Please add a recipe <%= link_to "here", new_recipy_path%></h2>
  </div>
<%else%>
  <div class='recipe-cont d-flex f-col j-center a-center'>
  <div class="flash d-flex a-center j-center">
    <% flash.each do |name, msg| %>
      <p class=<%= name %>><%= msg %> </p>
    <% end -%>
  </div>
  <%@recipes.each do |recipe|%>
    <div class='recipe-details-cont d-flex a-center'>
      <div class='recipe-name-delete d-flex j-center f-col'>
        <%= link_to "#{recipe.name}", recipy_path(recipe.id) %>
        <%if can? :destroy, recipe %>
              <%= button_to "Delete Recipe", recipy_path(recipe.id), :method => :delete %>
        <%end%>
      </div>
      <div class='description'>
        <p><%= recipe.description%></p>
      </div>
    </div>
  <%end%>
</div>
<%end%>

app/views/recipies/new.html.erb
<div class='login-page new-recipe-page d-flex a-center j-center f-col'>
  <%=form_with url: recipies_path, scope: :data do |f| %>
      <div class="field d-flex a-center j-center f-col">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, :required=>true %>
      </div>
      <div class="field d-flex a-center j-center f-col">
        <%= f.label :preparationtime, "Preparation Time"  %>
        <%= f.text_field :preparation_time, :required=>true %>
      </div>
       <div class="field d-flex a-center j-center f-col">
        <%= f.label :cookingtime, "Cooking Time"  %>
        <%= f.text_field :cooking_time, :required=>true %>
       </div>
        <div class="field d-flex a-center j-center f-col">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, :required=>true %>
      </div>
    <div class="public d-flex a-center j-center">
      <%= f.check_box :public %>
      <%= f.label :public?, "Public?" %>
    </div>
    <div class="actions d-flex a-center f-col">
         <%= f.submit "Create Recipe"%>
    </div>  
<% end %>

</div>

app/views/recipies/show.html.erb
<div class='recipe-show-page d-flex f-col a-center j-center'>
   <div class="flash d-flex a-center j-center">
    <% flash.each do |name, msg| %>
      <p class=<%= name %>><%= msg %> </p>
    <% end -%>
    </div>
    <div class='recipe-show-details d-flex f-col j-center'>
      <h1 class='d-flex a-center j-center'><%= @recipe.name %></h1>
      <div class='name-public d-flex a-center'>
        <h2><span><%="Preparation Time: #{@recipe.preparation_time}"%></span> <span></span></h2>
        <%if @recipe.public %>
          <div class='p-contain d-flex a-center j-center'>
            <h2>Public: </h2>
            <div class='name-public-btn'>
              <div class='div1'></div>
                 <button class='div1-btn'></button>
              </div>
          </div>
        <%end%>
      </div>
      <h2><%="Cooking Time: #{@recipe.cooking_time}"%></h2>
      <h2 class='desc'><%= "Description: #{@recipe.description}" %></h2>
      <div class= 'list-control d-flex a-center'>
        <%= link_to "Generate Shopping List", generate_shopping_list_index_path %>
        <% if can? :create, @recipe%>
            <%= link_to "Add new Ingredients", new_recipy_recipies_food_path(@recipe.id)%>
        <%end%>
      </div>
    </div>
    <%if @recipe_foods.empty?%>
        <div class='recipe-show-none'>
            <h1>No Ingredient added. Please add an Ingredient</h1>
        </div>
    <%else%>
      <div class='recipe-show-table'>
        <table class='recipe-table'>
          <tr>
            <th> Food </th>
            <th> Quantity </th>
            <th> Value </th>
            <% if can? :delete, @recipe%>
               <th> Actions </th>
            <%end%>
            
          </tr>
          <% @recipe_foods.each do |recipe_food| %>
            <tr class='tr'>
                <td><%=recipe_food.food.name%></td>
                <td><%= "#{recipe_food.quantity}#{recipe_food.food.measurement_unit}"%></td>
                <td><%= "$#{recipe_food.food.price.to_i * recipe_food.quantity.to_i}"%></td>
                <% if can? :delete, @recipe%>
                    <td> 
                      <%= button_to "Delete", recipy_recipies_food_path(@recipe.id, recipe_food.id), :method => :delete  %>
                    </td>
                 <%end%>
            </tr>
          <%end%>
        </table>
      </div>

    <%end%>
   

</div>

app/views/recipies_foods/new.html.erb
<div class='login-page new-recipe-food-page d-flex a-center j-center f-col'>
    <%=form_with url: recipy_recipies_foods_path, scope: :data do |f| %>
      <div class="field d-flex a-center j-center f-col" >
        <%= f.label :foodid, 'Food ID' %>
         <%= f.select :food_id, @foods.collect { |food| [food.name, food.id] }, class: "full-width", :prompt => 'Select an Ingredient', :required=>true %>
      </div>
      <div class="field d-flex a-center j-center f-col">
        <%= f.label :quantity, 'Quantity'  %>
        <%= f.number_field :quantity, :required=>true %>
      </div>
    <div class="actions d-flex a-center f-col">
         <%= f.submit "Add Ingredient"%>
    </div>
      
<% end %>
</div>

app/views/users/index.html.erb
<h1>view for user details</h1>

<div class='user-cont d-flex j-center a-center'>
 <div class='user-profile d-flex f-col a-center j-center'>
    <h1><%=current_user.name%></h1>
    <h2><%="No of Foods available: #{Food.all.length}"%></h2>
    <h2><%="No of Recipies available: #{Recipe.all.length}"%></h2>
 </div>
</div>